---
- name: gathering info ex1
  hosts: arista5
  gather_facts: True
  tasks:
    - debug:
        var: ansible_facts
    - eos_facts:
      register: device_facts
    - debug:
        var: device_facts
    - cli_command:
        command: show version
      register: device_version
    - debug:
        var: device_version

