---
- name: variables_ex3_task1
  hosts: nxos1
  tasks:
    - set_fact:
        my_new_variable: "{{ some_list[0] + ' ' + some_list[1] }}"
    - debug:
        var: my_new_variable
    - debug:
        var: ansible_host.upper()
