---
- name: ios configs
  hosts: cisco1
  gather_facts: False
  roles:
    - cisco_ios

- name: eos configs
  hosts: arista7
  gather_facts: False
  roles:
    - arista

- name: nxos configs
  hosts: nxos2
  gather_facts: False
  roles:
    - cisco_nxos
