---
- name: handlers ex1
  hosts: localhost
  gather_facts: False
  tasks:
    - debug:
        msg: unhandled task :(
    - debug:
        msg: handled task????
      notify: handle_this
    - debug:
        msg: handled task!
      notify: handle_this
      changed_when: True
  handlers:
    - name: handle_this
      debug:
        msg: STUFF HAS CHANGED, DONT FREAK OUT!
