---
- name: apis ex3
  hosts: nxos1
  gather_facts: False
  tasks:
    - uri:
        url: "https://{{ ansible_host }}:{{ ansible_httpapi_port }}/ins"
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: False
        method: POST
        body_format: json
        body:
          ins_api:
            version: "1.0"
            type: "cli_show"
            chunk: "0"
            sid: "1"
            input: "show version"
            output_format: "json"
      register: version
    - debug:
        var: version
