---
- name: gathering info ex4
  hosts: pan_firewalls
  gather_facts: False
  vars:
    provider:
      ip_address: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
  roles:
    - role: PaloAltoNetworks.paloaltonetworks
  tasks:
    - panos_facts:
        provider: "{{ provider }}"
      register: pan_facts
    - debug:
        msg: "{{ pan_facts.ansible_facts.ansible_net_version }}"
    - panos_object_facts:
        provider: "{{ provider }}"
        name_regex: "^web"
      register: pan_obj_facts
    - debug:
        var: pan_obj_facts
