---
- name: gathering info ex3
  hosts: pan_firewalls
  gather_facts: False
  vars:
    provider:
      ip_address: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
  roles:
    - role: PaloAltoNetworks.paloaltonetworks
  tasks:
    - panos_op:
        provider: "{{ provider }}"
        cmd: "show system info"
      register: output
    - xml:
        xmlstring: "{{ output['stdout_xml'] }}"
        xpath: /response/result/system/family
        content: text
      register: family
    - xml:
        xmlstring: "{{ output['stdout_xml'] }}"
        xpath: /response/result/system/vm-mode
        content: text
      register: mode
      when: family["matches"][0]["family"] == "vm"
    - debug:
        msg: "{{ mode['matches'][0]['vm-mode'] }}"
      when: family["matches"][0]["family"] == "vm"
